name: Test API connections

on:
    push:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests
              env:
                  ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
                  ZOTERO_GROUP_ID: ${{ secrets.ZOTERO_GROUP_ID }}
                  GRIST_API_KEY: ${{ secrets.GRIST_API_KEY }}
                  GRIST_DOC_ID: ${{ secrets.GRIST_DOC_ID }}
                  GRIST_TABLE_ID: ${{ secrets.GRIST_TABLE_ID }}
              run: pycheck -vv -s tests
